form/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("submit/<str:clubname>", views.form),
    path("views/<str:clubname>", views.club),
    path("leader/<int:form_id>", views.leader_view),
    path("time/<str:clubname>", views.time),
    path("cancel/<str:clubname>", views.cancel),
    path("select/<str:clubname>", views.select)
]

jamsinclub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include('account.urls')),
    path("about/", include('about.urls')),
    path("form/", include('form.urls')),
    path("leader/", include('leader.urls')),
    path("", include('index.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

form/models.py
import json
import datetime

from django.db import models
from django.utils.timezone import now

# Create your models here.

from about.models import ClubModel


class FormModel(models.Model):
    number = models.IntegerField()

    club = models.ForeignKey(ClubModel, on_delete=models.PROTECT)

    # club = models.CharField(max_length=10)

    section = models.JSONField(
        encoder=json.JSONEncoder,
        decoder=json.JSONDecoder
    )

    submit_at = models.DateTimeField(auto_now_add=True)

    archive = models.BooleanField(default=False)

    # 추가합격은 additional, 추가모집은 extra라 명명합시다.
    # A = 추가합격 대상자 (대기) / V = 추가합격 대상자 (표시) / S = 동아리 입부 선택 / G = 입부 포기
    RESULTS = [('W', 'WAIT'), ('P', 'PASS'), ('F', 'FAIL'),
               ('A', 'ADDITIONAL_PASS'), ('V', 'ADDITIONAL_PASS_VISIBLE'), ('S', 'SELECTED'), ('G', 'GIVE_UP')]
    first_result = models.CharField(max_length=1, choices=RESULTS, default='W')
    second_result = models.CharField(max_length=1, choices=RESULTS, default='W')

    additional_rank = models.IntegerField(null=False, default=0)

    # 추가모집 지원서일 경우 - 추가모집 결과는 FIRST_RESULT에 저장
    is_extra = models.BooleanField(default=False)
    # time = models.CharField(max_length=100, default='', blank=True)

    time_data = models.DateTimeField(null=True, blank=True)


'''
    동아리 부장이 TimeModel을 생성하여 시간을 지정하고,
    지원자가 시간을 선택하면 해당 지원자의 form이 연결되도록 합시다.
    (아니면 그냥 지원자 account를 연결해도 무방하구요)
    
    time_data에 json 형식으로 저장하는 방식 자체가 위험합니다!
    이 때문에 작년에 오류가 났던 것이구요.
    TimeModel에는 시간을 저장하고, 각각의 합격된 FormModel과 연결하여
    장고 모델로서 활용할 수 있도록 합시다.
    
    이렇게 구조가 변경되면 총 네 가지가 변경되어야 하겠네요.
    1. 지원자의 시간 선택 페이지: form/views.py time() (+ form/templates/time.html)
    2. 부장의 면접시간 지정 페이지: leader/views.py time_config() (+ leader/templates/time_config.html)
    3. 기존 부원들의 지원자 면접시간 확인 페이지: leader/views.py view_time() (+ leader/templates/view_time.html)
    4. 메인페이지 시간 확인 부분: index/views.py 
    
    화이팅입니다!!
'''


class TimeModel(models.Model):
    time_start = models.DateTimeField(default=now)  # 면접 시작시간
    time_end = models.DateTimeField(default=now)  # 면접 종료시간

    current = models.IntegerField(default=0)  # 현재 면접 예약 인원수
    number = models.IntegerField(default=10)  # 시간당 면접 정원

    form = models.ManyToManyField('FormModel', related_name='time_form+', through='FormtoTime',blank=True)
    club = models.ForeignKey(ClubModel, related_name='time_club+', on_delete=models.SET_NULL, null=True)

    # @TODO: 생각해보니 하나의 TimeModel에 여러 FormModel이 연결될 수 있음. ManyToMany로 바꿔야 할듯.
    # 그리고 FormModel에서 time_data 없애고, ManyToManyField의 related_name 속성 이용해서 연결하기.
    # 이왕 하는김에 다른 데이터들도 related_name으로 다 바꿔두면 좋은...데 시간이 없넹ㅎ

    # 2차 면접 시간 데이터
    # time_data = models.JSONField(encoder=json.JSONEncoder, decoder=json.JSONDecoder, default=list)

    # clubmodel 은 timemodel, timemodel 은 formmodel 참조

class FormtoTime(models.Model):
    form = models.ForeignKey(FormModel, on_delete=models.SET_NULL, null=True, blank=True)
    time = models.ForeignKey(TimeModel, on_delete=models.SET_NULL, null=True, blank=True)

index/templates/index/clubRelation.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'index/clubRelation.css' %}?v=3">
{% endblock %}

{% block content %}
    <div class="bg">
        <div class="title">
            <h1>잠신고 동아리 <br class="mobile">지원 누리집</h1>
            <p>운영 기간: 02.20 ~ 03.22</p>
        </div>
        <hr>
        <h3 class="period_info">기간 안내</h3>

        <div class="period">
            <h4>1차 서류 지원</h4>
            <h5>3/4 ~ 3/23 16:00</h5>
            <p>사이트에서 동아리별 양식을 작성하여 지원합니다.</p>
        </div>

        <div class="period">
            <h4>1차 서류 결과 발표</h4>
            <h5>3/12 09:00</h5>
            <p>사이트를 통해 1차 서류합격이 발표됩니다.</p>
        </div>

        <div class="period">
            <h4>면접시간 선택</h4>
            <h5>3/12 12:00~</h5>
            <p>사이트를 통해 1차 합격된 동아리의 면접 시간을 선택합니다.</p>
            <p>면접 시간은 동아리에서 지정한 시간 중에 선택할 수 있으며, 선착순으로 진행됩니다.</p>
        </div>

        <div class="period">
            <h4>2차 대면 면접</h4>
            <h5>3/13 ~ 3/19</h5>
            <p>방과 후 본인이 선택한 시간에 학교에서 면접을 실시합니다.</p>
            <p>장소는 동아리마다 다르니 면접 안내 문자를 확인하세요.</p>
        </div>

        <div class="period">
            <h4>합격자 발표 및 입부</h4>
            <h5>3/20 00:00 ~ 12:00</h5>
            <p>사이트를 통해 동아리별 최초 합격자 발표가 진행됩니다.</p>
            <p>합격자는 자신이 합격된 동아리 중 한 곳을 사이트에서 선택하여 입부할 수 있습니다.</p>
            <p>동아리를 한번 선택하고 나면 변경할 수 없으며, 자동으로 다른 동아리의 추가합격 명단에서 제외되고, 마지막 추가모집 기간에 지원할 수 없습니다.</p>
            <p>이때 동아리를 선택하지 않으면, 해당 동아리의 합격이 취소되며 이후 번복할 수 없습니다.</p>
        </div>

        <div class="period">
            <h4>1~4차 추가합격 발표</h4>
            <h5>3/20 12:20~<br>14:00~ 16:00~ 18:00~</h5>
            <p>점심시간부터 추가합격이 진행됩니다.</p>
            <p>본인이 추가합격 대상자인 경우 사이트에서 입부를 선택할 수 있습니다.</p>
            <p>최초 합격자와 동일하게 이 선택은 번복할 수 없습니다.</p>
        </div>

        <div class="period">
            <h4>추가 모집 기간</h4>
            <h5>3/20 20:00 ~ 3/21 20:00</h5>
            <p>모집 인원이 남은 동아리들을 대상으로 추가 모집이 진행됩니다.</p>
            <p>사이트를 통한 서류 지원만 진행되며, 여러 동아리에 동시 지원이 가능합니다.</p>
            <p>부장은 추가모집 기간 내 언제든 지원자의 합격을 결정할 수 있고, 그 즉시 지원자의 입부가 확정됩니다.</p>
            <p></p>
        </div>

        <div class="period">
            <h4>일반동아리 조직</h4>
            <h5>3/22</h5>
            <p>금요일 6교시 창체 시간에 상설동아리에 소속하지 않은 학생들을 대상으로 일반동아리를 조직합니다.</p>
            <p>이때 상설동아리에 소속한 학생들은 일반동아리를 선택할 수 없습니다.</p>
        </div>

        <hr>
        <h4 class="with">모든 상설 동아리와 함께합니다.</h4>
        <div class="rel">
            {% for club in clubs %}
                <img class="logo" style="" src="{{ club.logo_url }}" onclick="changeNav('club_{{ club.code }}', '/about/{{ club.code }}');">
            {% endfor %}
        </div>
        <h4 class="by">누리집 개발: 공학동아리 로델라<br>담당: 창의체험부</h4>
    </div>

    <script>
        selectNav('home');
    </script>
{% endblock %}

index/templates/index/index.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'index/index.css' %}?v=11">
{% endblock %}

{% block module %}
    {{ block.super }}
    <!--<script src="https://code.jquery.com/jquery-3.6.3.min.js"></script>-->
    <script src="{% static 'index/index.js' %}?v=3"></script>
{% endblock %}

{% block content %}
    <div class="upper_container">
        <!--
        <div id="banner" style="background-image: url('{{ banner_club.index_banner_image.image.url }}')">
            <div class = 'inner_banner' onclick="return changeNav('club_{{ banner_club.code }}', '/about/{{ banner_club.code }}');">
                <strong style="color: {{ banner_club.index_banner_color }}">{{ banner_club.name }}</strong>
                <p>{{ banner_club.index_banner_description }}</p>
            </div>
        </div>-->
        {% for club in banner_clubs %}
        <div class="banner banner-{{ club.code }}" style="display: none;">
            <div class="inner_banner" onclick="return changeNav('club_{{ club.code }}', '/about/{{ club.code }}');">
                <strong style="color: {{ club.index_banner_color }}">{{ club.name }}</strong>
                <p>{{ club.index_banner_description }}</p>
            </div>
        </div>
        <style>
            .banner-{{club.code}} {
                background-image: url('{{ club.index_banner_image.image.url }}');
            }
        </style>
        {% endfor %}
    </div>
    <h2 class="status" onclick="return changeNav('home', '/club_relation')">
        지금은 <span class="current">{{ status.get_current_display }}!</span>
    </h2>
    {% if status.notice %}
        <h4 class="notice">※ {{ status.notice }}</h4>
    {% endif %}


    {% if user.is_authenticated %}
        <div class="outer-container">

            <div class = 'dong_ari'>
                <h2>지원한 동아리</h2>
                {% if forms|length > 0 %}
                    <div class="submits">
                        {% for form in forms %}
                            <div class="submit">
                                <h3>{{ form.club.name }}</h3>
                                {% if form.first_result == 'P' %}
                                    <p class="pass">1차 서류 합격</p>
                                {% elif form.first_result == 'F' %}
                                    <p class="fail">1차 불합격</p>
                                {% else %}
                                    <p class="wait">1차 결과 대기중</p>
                                {% endif %}
                                {% if form.second_result == 'P' %}
                                    <p class="pass">2차 합격</p>
                                {% elif form.second_result == 'F' %}
                                    <p class="fail">
                                    {% if status.current == 'SECOND_RESULT' %}
                                        최초 불합격
                                    {% elif status.current == 'ADD_FIRST_RESULT' %}
                                        1차 추합 불합격
                                    {% elif status.current == 'ADD_SECOND_RESULT' %}
                                        2차 추합 불합격
                                    {% elif status.current == 'ADD_THIRD_RESULT' %}
                                        3차 추합 불합격
                                    {% elif status.current == 'ADD_FOURTH_RESULT' %}
                                        4차 추합 불합격
                                    {% else %}
                                        2차 불합격
                                    {% endif %}
                                    </p>
                                {% elif form.second_result == 'S' %}
                                    <p class="select">가입 확정</p>
                                {% elif form.second_result == 'G' %}
                                    <p class="give_up">가입 포기</p>
                                {% elif form.second_result == 'V' %}
                                    <p class="additional_pass">2차 추가합격</p>
                                {% else %}
                                    {% if form.first_result == 'F' %}
                                        <p>　</p>
                                    {% else %}
                                        <p class="wait">면접 결과 대기중</p>
                                    {% endif %}
                                {% endif %}
                            {% if form.second_result == 'P' or form.second_result == 'V' %}
                                <button class="select" onclick="enterClub('{{ form.club.code }}', '{{ form.club.name }}')">동아리 가입하기</button>
                            {% else %}
                                <button onclick="return changeNav('club_{{ form.club.code }}', '/form/views/{{ form.club.code }}');">지원서 보기</button>
                            {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <p class="infotext">동아리에 지원해보세요!</p>
                {% endif %}
            </div>

            <div class = 'interview'>
                <h2>면접 시간</h2>
                <div class="submits">
                    {% for form in forms %}
                        {% if form.first_result == 'P' %}
                            <div class="submit">
                                <h3>{{ form.club.name }}</h3>
                                {% if form.club.time_use %}
                                    {% if form.time_data %}
                                        <!-- 시간 취소 기능 추가 -->
                                        <button style="color: red;" onclick="CancelAlert('{{ form.club.name }}')">시간 취소하기</button>
                                        <p>{{ form.time_data }}</p>
                                    {% else %}
                                        <button style="color: green;" onclick="return changeNav('club_{{ form.club.code }}', '/form/time/{{ form.club.code }}')";>시간 선택하기</button>
                                    {% endif %}
                                {% else %}
                                    <span style="color: grey;">별도 안내 예정</span>
                                {% endif %}
                                <h5>장소: {{ form.club.location }}</h5>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
<!--            <p style="color: grey; text-align: center;">1차 합격된 동아리에서 면접 안내 문자를 받지 못했다면, 해당 동아리에 문의해보세요.</p>-->
            </div>

            <div class = 'my_info'>
                <h2>내 정보</h2>
                <strong>{{ user.id }} {{ user.name }}</strong>
                <p>{{ user.phone }}</p>
                <button onclick="location.href = '/account/logout'">로그아웃</button>


                {% if user.leader_of or user.member_of %}
                    <br><br>
                    <span><b>부원 전용 메뉴:</b></span>
                    <br>
                    <a href="/leader/view_forms">지원서 보러 가기</a>
                    <br>
                    <a href="/leader/view_time">면접시간 보러 가기</a>
                    <br>
                    <a href="/leader/view_selection">동아리 선택 현황 보러 가기</a>
                {% endif %}

                {% if user.leader_of %}
                    <br><br>
                    <span><b>부장 전용 메뉴:</b></span>
                    <br>
                    <a href="/leader/club_config">동아리 관리</a>
                    <br>
                    <a href="/leader/time_config">면접 시간 관리</a>
                {% endif %}
            </div>
        </div>
    {% else %}
        <div class="login_wrapper">
            {% include 'account/login.html' %}
        </div>
    {% endif %}

    <script>
        selectNav('home');
        var user_id = '{{ user.id }}';
        var user_name = '{{ user.name }}';
    </script>
{% endblock %}